//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AttendanceEntities : DbContext
    {
        public AttendanceEntities()
            : base("name=AttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<tblAuditTray> tblAuditTray { get; set; }
        public virtual DbSet<tblConfig> tblConfig { get; set; }
        public virtual DbSet<tblCourseAllocation> tblCourseAllocation { get; set; }
        public virtual DbSet<tblSetupDept> tblSetupDept { get; set; }
        public virtual DbSet<tblSetupFaculty> tblSetupFaculty { get; set; }
        public virtual DbSet<tblSetupInstitution> tblSetupInstitution { get; set; }
        public virtual DbSet<tblsetupRole> tblsetupRole { get; set; }
        public virtual DbSet<tblSetupSemester> tblSetupSemester { get; set; }
        public virtual DbSet<tblSetupSession> tblSetupSession { get; set; }
        public virtual DbSet<tblSetupVenue> tblSetupVenue { get; set; }
        public virtual DbSet<tblsetupCourse> tblsetupCourse { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblNewCourseAllocation> tblNewCourseAllocation { get; set; }
        public virtual DbSet<tblCourseRegistration> tblCourseRegistration { get; set; }
        public virtual DbSet<tblCaptureAttendance> tblCaptureAttendance { get; set; }
    
        public virtual int GenericAudit(string tableName, string pKName, string changedBy, string oldData, string newData)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var pKNameParameter = pKName != null ?
                new ObjectParameter("PKName", pKName) :
                new ObjectParameter("PKName", typeof(string));
    
            var changedByParameter = changedBy != null ?
                new ObjectParameter("ChangedBy", changedBy) :
                new ObjectParameter("ChangedBy", typeof(string));
    
            var oldDataParameter = oldData != null ?
                new ObjectParameter("OldData", oldData) :
                new ObjectParameter("OldData", typeof(string));
    
            var newDataParameter = newData != null ?
                new ObjectParameter("NewData", newData) :
                new ObjectParameter("NewData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenericAudit", tableNameParameter, pKNameParameter, changedByParameter, oldDataParameter, newDataParameter);
        }
    }
}
