//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCaptureAttendance
    {
        public int attendanceid { get; set; }
        public int semid { get; set; }
        public string semester { get; set; }
        public int sessid { get; set; }
        public string session { get; set; }
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public bool Attend { get; set; }
        public System.DateTime Date { get; set; }
        public string StaffID { get; set; }
        public string CourseCode { get; set; }
    }
}
