//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourseAllocation
    {
        public int Allocid { get; set; }
        public int courseid { get; set; }
        public int venueid { get; set; }
        public int staffid { get; set; }
        public int sessid { get; set; }
        public int semid { get; set; }
    }
}
