//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewCourseAllocation
    {
        public int Allocid { get; set; }
        public int Semid { get; set; }
        public string code { get; set; }
        public int sessionid { get; set; }
        public string semester { get; set; }
        public string Session { get; set; }
        public string Dept { get; set; }
        public int Deptid { get; set; }
        public string StaffId { get; set; }
        public int Venueid { get; set; }
        public string StaffName { get; set; }
        public string Venue { get; set; }
    }
}
