//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetupVenue
    {
        public int venid { get; set; }
        public int deptid { get; set; }
        public string name { get; set; }
    }
}
