//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsetupRole
    {
        public int roleid { get; set; }
        public string role { get; set; }
    }
}
