//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetupSession
    {
        public int sessid { get; set; }
        public string session { get; set; }
    }
}
