//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int userid { get; set; }
        public string SchID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string Dept { get; set; }
        public int Deptid { get; set; }
        public int Statusid { get; set; }
    }
}
